### ISSUE TITLE
Enum instances for seconds/minutes/milliseconds

### ISSUE THREAD

**Issue by AKST** [purescript/purescript-datetime#12]
Right now there are no instances of `Enum` for the time intervals? Is this by design, or just something that has not yet been implemented? If has not been implemented yet I would be happy to put something together and submit a pull request.

**Edit**: Actually it looks like there are a few missing instances.

The reason I'm looking for instances of `Enum` is the `fromEnum` method of the typeclass, as I'm trying to generate a string representation.

**Comment by garyb** [comment]
`Enum` instances would be great, they're just missing due to an oversight.

**Comment by AKST** [comment]
Oh okay, I'll see what I can look together then.

**Comment by garyb** [comment]
A related class that isn't usable just yet, is `Bounded`. It's coming in the next compiler release, as it's part of the class hierarchy in `Prelude`. I added instances for that in this PR #13 I opened earlier (will be merged when we update the compiler), I'm not sure it's quite strong enough for what you're after though.

**Comment by AKST** [comment]
Oh right, I had a quick look at it and it doesn't seem to have the functionality you get from `fromEnum` where it takes the enum and returns a `Number`, (at I don't think it does). That was the main functionality I was looking for, so I didn't have write a time unit specific code to extract the number out of each time type. 

So I can turn this.

```purescript
ddmmyyDate :: Date -> String
ddmmyyDate date = day ++ "/"  ++ month ++ "/" ++ year where
  month = date # month # fromEnum # show
  year  = case year date of
    Year n -> show (toNumber n)
  day   = case Date.dayOfMonth date of
    DayOfMonth n -> show (toNumber n)
```

Into this.

```purescript
ddmmyyDate :: Date -> String
ddmmyyDate date = day ++ "/"  ++ month ++ "/" ++ year where
  day   = date # dayOfMonth # toString
  month = date # month # toString
  year  = date # year # toString

  toString x = x # toEnum # show
```

But also for the `Time` type as well, but I'm not sure if using `fromEnum` of `Enum` would be the best approach to solve this problem, I just went with it because it was polymorphic. 

There are bindings for [Moment.js](https://github.com/CapillarySoftware/purescript-moment) for purescript which handles date formatting, but the API doesn't interact with this library, while `moment.js` does interact with javascript objects. Maybe I should head over there and see if they interested incorporating it in the API bindings.

However if Enum bindings are still desired for the rest of the time types, I can put something together but it might just mean waiting for the changes from that PR to land.

**Comment by garyb** [comment]
Closing this as thing have moved on somewhat! We do have `Enum` instances now too.
