### ISSUE TITLE
Overflow with Int and milliseconds

### ISSUE THREAD

**Issue by nwolverson** [purescript/purescript-datetime#17]
Using this with PS 0.7. Millisecond values, e.g. from `toEpochMilliseconds` of today overflows Int and ends up -ve. Particularly an issue as this is used under the hood and not just this conversion.

(See also `new Date().getTime() | 0`)

**Comment by garyb** [comment]
Argh! Will have to switch it back to `Number` then I guess.

**Comment by garyb** [comment]
Resolved by #18
