### ISSUE TITLE
add binding for toISOString

### ISSUE THREAD

**Issue by jonsterling** [purescript/purescript-datetime#28]
It would be great to be able to render a `Date` as an ISO 8601 string! I'll probably submit a patch shortly, as I've inlined this in another project.

**Comment by garyb** [comment]
Resolved by #20

**Comment by texastoland** [comment]
Missing again? Also the old parse implementation didn't use JS `Date.parse`?

**Comment by garyb** [comment]
It's in `purescript-js-date`: https://github.com/purescript-contrib/purescript-js-date/blob/11f861b9a6cc6af56ae315e78440181fe89ae8c1/src/Data/JSDate.purs#L204-L206

This library intentionally includes no parsers or printers, it's mainly here to provide a common set of types for represening dates and leaving the other things up to libraries like [`purescript-formatters`](https://github.com/slamdata/purescript-formatters).

**Comment by texastoland** [comment]
WFM I'll close #38 👍

**Comment by jmackie4** [comment]
@texastoland if it helps, I wrote a tiny `DateTime` wrapper that handles encoding/decoding to/from ISO strings :) [pursuit link](https://pursuit.purescript.org/packages/purescript-datetime-iso/)
