### ISSUE TITLE
Issues with getting dates out of strings

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-datetime#30]
I am aware of two problems with `fromString`:

1. `Date.parse` can depend on the current system timezone; for ISO formats, it's UTC, but for other formats, it uses the system timezone. However the type of `fromString` is `String -> Maybe Date`. I think it should be `forall eff. String -> Eff (locale :: Locale | eff) (Maybe Date)`.
2. `Date.parse` is probably not what you want to use in most cases, and its behaviour can be quite surprising (see http://ircbrowse.net/browse/purescript?id=301057&timestamp=1460055027#t1460055027 and the following page). In fact the MDN page that the docs link to explicitly discourages its use. Therefore I don't think we should be suggesting it as the default choice (as we currently do by calling it `fromString` and the other one `fromStringStrict`). Can we switch these around so that `fromStringStrict` becomes `fromString`, and `fromString` gets some other name?

**Comment by garyb** [comment]
Yeah, it's not good.

I'm trying to rework the whole library to not be dumb, moving to a pure "epoch milliseconds" representation rather than having a `JSDate` internally (although I'll probably fall back to that internally to do most of the logic).

**Comment by hdgarrood** [comment]
Maybe this would be a good area to apply the same technique as we have with purescript-dom: a low level library with bindings which are as close as possible to the underlying API, and then opinionated, higher level things on top?

**Comment by garyb** [comment]
That's kinda what I'm going for: a bunch of pure data types, and then stuff under `Control.Monad.Eff.DateTime` (or something) for the JS side of things.

**Comment by hdgarrood** [comment]
Come to think of it, maybe we should consider a datetime library in pure PS? I don't think it will be too hard to do better than the JS Date api, and this way, it will work in other backends, too.

**Comment by garyb** [comment]
That's what I want too really... but I didn't want to deal with the logic of it, when you get into dealing with leap seconds, etc. However, it appears JS also ignores leap seconds, so maybe we can do a better job ourselves. I'd definitely appreciate any help on that front.

**Comment by hdgarrood** [comment]
I think it's reasonable to ignore leap seconds, even the Haskell `time` library does. (See the comments for `UTCTime`: http://hackage.haskell.org/package/time-1.6/docs/Data-Time-Clock.html)

**Comment by garyb** [comment]
I think this is safe to close now, since it refers to the previous design.
