### ISSUE TITLE
Date type without Time component

### ISSUE THREAD

**Issue by FrigoEU** [purescript/purescript-datetime#32]
Hey,

Often I'm in need of a Date type without a Time component. So far I've been making my own, I call it CalendarDate, that's just:

```
data CalendarDate = CalendarDate Year Month DayOfMonth
```

I'm wondering, do you think this would be a good idea to incorporate in the core library?

**Comment by garyb** [comment]
Yeah, definitely. I mentioned in some of the other issues/PRs that I'm working on a new version of this library that won't be dependent on JSDate, so having dates without time will be part of that. I just need to find some time to get it done...

**Comment by FrigoEU** [comment]
Ok great. I don't want to intrude, but I can help with that. I'm working on a couple small apps, all need solid Date functionality, so I'm up for putting in some work to create a solid foundation. Let me know what you have/still need done in case you could use some help.

**Comment by garyb** [comment]
That'd be awesome. At the moment there's not a great deal of code, it's mostly a bunch of notes on what I'd like the library to provide and handle. I'll try and find some time today to write up an outline of what I have in mind.

**Comment by garyb** [comment]
We now have this in the v1 release - there is a `Date` constructor independent from `DateTime`.
