### ISSUE TITLE
DateTime library redesign

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-datetime#33]
Here's my thinking so far.

``` purescript
-- Quantities
-- Using `Number` to allow fractional values, but also larger ranges
newtype Hours = Hours Number
newtype Minutes = Minutes Number
newtype Seconds = Seconds Number
newtype Milliseconds = Milliseconds Number

-- Date parts
newtype Year = Year Int
data Month = January | February | March ...
newtype Day = Day Int
data Weekday = Monday | Tuesday | ...

-- Time parts
newtype Hour = Hour Int
newtype Minute = Minute Int
newtype Second = Second Int
newtype Millisecond = Millisecond Int
data DayPart = AM | PM
data Hour12 = Hour12 Hour DayPart

-- UTC dates. Most manipulation operations will only operate on these.
data Date = Date Year Month Day
data Time = Time Hour Minute Second Millisecond
data DateTime = DateTime (Date a) (Time a)

-- Locale-offset values. Constructed from UTC values with an offset, probably
-- only usable for rendering... there may be a limited set of operations that
-- work also.
--
-- `LocalValue` is a Functor so the inner value can be manipulated without
-- explicit unwrapping/rewrapping
--
-- `LocaleName` is for things like "GMT", "MDT", "CET", etc.
newtype LocaleName = LocaleName String
data Locale = Locale (Maybe LocaleName) Minutes
data LocalValue a = LocalValue Locale a
type LocalDate = LocaleValue Date
type LocalTime = LocaleValue Time
type LocalDateTime = LocaleValue DateTime
```

- Dates will only be constructable via smart constructors, converted from quantities, or by parsing.
- When creating a date from a quantity, it will be treated as relative to the unix epoch.
- We'll only provide a handful of common formats for parsing from in the library, a format string language could be provided in another library if we ever wanted it. I tend to prefer real parsers anyway. :wink:
- Any format we can parse we can also render from a date.
- Alternatively, maybe we don't do any parsing/pretty printing of dates in this library, and handle it all in a separate place. That has a certain appeal too as it will reduce the number of required dependencies to use dates.

There will be some kind of `TimeSpan` quantity constructed from `DateTime`s as well as the numeric quantities, but I haven't fully thought out what additional operations a `TimeSpan` might have relative to the other quantities. It will probably be possible to construct a `TimeSpan` from other combinations of values too, two `Time`s only, two `Date`s only, another quantity, etc. just that it will use `DateTime` as its internal representation.

We'll have more options for manipulating dates with this formulation too, as we will be able to add or subtract quantities to dates without having to deconstruct and reconstruct them manually.

The main hurdle at the moment that needs figuring out now is an algorithm for converting `DateTime`s to and from the unix epoch. I didn't have a great amount of success trying to find suitable algorithms for it on the web when I last looked.

Anyway, there are the things I've been kicking around while thinking about where to take this, but I'm definitely open to changing things. The one thing I don't think we can forgo is the unix epoch conversions though, as that's basically our interface to JS dates. It's a generally a handy representation too when you need to squash it into a single portable value of some kind.

/cc @hdgarrood @FrigoEU

**Comment by hdgarrood** [comment]
Looks sensible to me. Can we borrow JS' algorithm for converting to and from the unix epoch for now? I think `Date.UTC` will convert from a `DateTime` to the unix epoch, and the reverse could be done with `new Date(epoch).getUTC{Year,Month,Day,...}`. I realise I previously said it would be nice to have this as a pure PS library but I think it would be acceptable to use bindings to JS `Date` objects as an implementation detail to start with, so that we don't have to worry about writing that algorithm ourselves.

**Comment by jdegoes** [comment]
Well, here's my 2 cents:

1. This seems like a sensible design, however, note that your notion of `Date` and `DateTime` are actually *underspecified*. They pretend there is such a thing as a date or a time without a notion of calendar / locale. That's not true, and this pretension will lead to bugs in code.
2. The [Java ecosystem](http://www.threeten.org/articles/index.html) has what is probably the best design for a date/time library. ThreeTen is the successor to JodaTime, which was designed as a replacement for Java's broken date/time. A lot of effort and thought has gone into the design. I would not hastily make any different design decisions.

**Comment by garyb** [comment]
Re: 1. Yeah, I didn't mention, but Gregorian UTC is the intended canonical form.

I'll take a look at ThreeTen though, thanks!

**Comment by FrigoEU** [comment]
1. I would be in favor of keeping parsing and printing in a seperate library. As you said, it feels like this would make the core library easier to use. Also easier to get to a first working version.
2. I really like the terminology being used in ThreeTen. Took me a moment to get used to it, but it seems clear. I'd be in favor of reusing that.
2. Do I understand correctly that the conversion from DateTime to/from unix epoch would be, in ThreeTen terminology the converison from Instant to ZonedDateTime and back? I'm in favor of hdgarrood's suggestion to, at least for now, use JS Dates for it. A JS Date is essentially a ZonedDateTime I think.
3. I looked at ThreeTen, and it seems in later iterations (http://www.threeten.org/threetenbp/apidocs/index.html) they've added OffsetTime and OffsetDateTime types. With these they make the distinction between +0100 and +0100 Europe/Paris. I'm unsure if you need this kind of extra distinction.
4. Most libraries seem to have all the heavy timezone stuff in a seperate package (eg: http://momentjs.com/timezone/). In many applications you don't need these conversions all the time, so keeping them somewhere seperate seems to be a good idea?
5. Having an Instant newtype that represents milliseconds from the unix epoch seems very useful as well.

**Comment by hdgarrood** [comment]
I don't think JS dates are quite the same as ZonedDateTimes, I'd describe them as just a wrapper around a Number value representing milliseconds since unix epoch, together with some methods for asking for the day of month, month, hour of day, etc, either in UTC or in the system locale. In particular I don't think you can do anything with any locale other than the system locale with just vanilla JS dates.

I think the extra distinction between OffsetTime and OffsetDateTime is because although there may be lots of regions on +0100 at one particular moment in time, they may have different dates for when daylight saving starts and ends (whereas if you also know Europe/Paris, you do know when daylight saving starts and ends).

**Comment by FrigoEU** [comment]
I stand corrected. JS Dates indeed don't have a TimeZone component inside. My bad.

**Comment by garyb** [comment]
- Re: 3. I wasn't clear there, I meant in the sense of converting a milliseconds quantity since the unix epoch into a `DateTime` value.
- Re: 4. We do have that distinction here, in that a `Locale` has a `Maybe LocaleName` as well as the `Minutes` offset. I'll perhaps change that a bit so that `Minutes` is just any quantity.
- Re: 6. `Instant` might well be worthwhile, I was just thinking of using a `Milliseconds` quantity for that.

Having looked at ThreeTen, the current proposal here isn't too far off what the core package provides. If we were going to provide a super comprehensive library, I'd probably prefer to build it in separate pieces, similar to the way we ended up splitting `argonaut`.
