### ISSUE TITLE
IsForeign instance for dates

### ISSUE THREAD

**Issue by epost** [purescript/purescript-datetime#36]
What's the current thinking on how parsing dates should be done? I noticed some of the `fromString` functions have disappeared in the rewrite, and I'd like to be able to have an `IsForeign` instance for dates.

**Comment by garyb** [comment]
I'd suggest date parsing should be done with a real parsing library like `parsers` or `string-parsers` - we could define a pattern language for parsing (and printing) at some point, but I see that as being a separate library in contrib too (it will most likely depend on one of those parsing libraries, and they are located in contrib).

`IsForeign` would be something that belongs in [`purescript-js-date`](https://github.com/purescript-contrib/purescript-js-date), given the representations here are now a real PureScript ADTs. It definitely should be defined in there too, just an oversight on my part!

**Comment by epost** [comment]
Cool, I'll have a look at that then, thanks!
