### ISSUE TITLE
add Traversable instance for LocalValue

### ISSUE THREAD

**Issue by mjhoy** [purescript/purescript-datetime#42]
I want to be able to write, for instance:

``` purescript
now <- nowDateTime
let now' = (traverse (adjust $ Minutes 3.0) now)
```

where `now'` is a `Maybe LocalDateTime`.

Using the functor instance, e.g., `map (adjust $ Minutes 3.0) now` gives me a `LocalValue (Maybe DateTime)` which isn't so useful.

**Comment by mjhoy** [comment]
And, I'm sure it's simple, but I'd be willing to work on a PR if you think it's a good idea! Thanks.

**Comment by garyb** [comment]
Sure! Sounds good to me.

**Comment by mjhoy** [comment]
Just curious: does this package require a specific compiler version? I run into a bunch of errors when building master on 0.9.3. (I'm fairly new to the purescript ecosystem so I'm not sure how to approach this.)

**Comment by garyb** [comment]
Ah yes, the v2.0.0 version requires psc 0.10.x. We've just done a mass update of the core libraries for 0.10, most of contrib is done, and we're working through the rest.
