### ISSUE TITLE
Add `adjust` for `Date`

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-datetime#44]

**Comment by anilanar** [comment]
What does `adjust` do?

**Comment by garyb** [comment]
@anilanar there's a version for `Time` and `DateTime` already: https://github.com/purescript/purescript-datetime/blob/2ff38080622e43105485418bbca6b394ee6fd417/src/Data/DateTime.purs#L57-L64

It adjusts the value by a duration - in the case of dates it should probably `floor` the change, so it requires increments of at least 24 hours to have an effect... `round` could probably work too, I'm not sure which is best. Whichever we use should be stated in a doc-comment. :)

**Comment by anilanar** [comment]
@garyb Yup, I figured that a minute later I posted. I'll give this a try.

**Comment by anilanar** [comment]
I'll work on this after/when #56 gets merged as it will make more sense to use a single `adjustImpl` for both `Date` and `DateTime` which I'll put into a `Data.Date.Internal` module.
