### ISSUE TITLE
Dates before the year 1901 are not handled correctly by `canonicalDate` and `exactDate`

### ISSUE THREAD

**Issue by tdammers** [purescript/purescript-datetime#46]
The `Year` type faithfully represents all the years from -271820 to 275759, but passing, e.g., `toEnum 1` into `canonicalDate` produces a date in the year 1901, not the year 1 as one would expect.

Example code:

    show <<< year $ canonicalDate (fromMaybe bottom $ toEnum 1) January bottom

...produces `"(Year 1901)"`, instead of `"(Year 1)"`.

The culprit seems to be on the JavaScript side of things; while the `Date` type can represent dates like '0001-01-01', creating them the way `canonicalDate` does, which is `new Date(Date.UTC(y, m - 1, d))`, "helpfully" "fixes" the year number to after 1900.

**Comment by garyb** [comment]
Ughh thanks, yeah I guess we'll have to massage the input values some if we want to keep using the JS stuff to do the date logic. Well, we don't really, but I also don't trust myself to implement it correctly in PS either 😕

**Comment by tdammers** [comment]
Figured this much.

In case it helps, some quick toying with JS's `Date` ctor reveals that you can construct the desired dates if you pass in a string, like so:

    > new Date('0001-01-01')
    0001-01-01T00:00:00.000Z

...but getting the format wrong breaks things rather badly:

    > new Date('0001-1-1')
    2000-12-31T23:00:00.000Z

**Comment by anilanar** [comment]
I think this can be solved in the JS-land, at least I'll give it.
