### ISSUE TITLE
Can't build this with current `purs`: 3 compiler errors related to `Data.Generic.Generic`

### ISSUE THREAD

**Issue by metaleap** [purescript/purescript-datetime#66]
Using current `purs` `master` branch (prints as "v0.11.6 dev build"), this build error when simply rebuilding a project where I did just `bower install purescript-datetime` (it picked `3.4.0` btw) prior, not even importing or using this lib anywhere:

    [00:00 _ ~/c/ps/gonad-demos]$ pulp build -- --dump-corefn
    * Building project in ~/c/ps/gonad-demos
    Compiling Data.Time.Component
    Compiling Data.Date.Component
    Compiling Data.Time.Duration
    Error 1 of 3:
    
      at bower_components/purescript-datetime/src/Data/Date/Component.purs line 23, column 8 - line 23, column 44
        
        Cannot derive a type class instance for
                                   
          Data.Generic.Generic Year
                                   
        since instances of this type class are not derivable.
    
    
      See https://github.com/purescript/documentation/blob/master/errors/CannotDerive.md for more information,
      or to contribute content related to this error.
    
    Error 2 of 3:
    
      at bower_components/purescript-datetime/src/Data/Time/Component.purs line 24, column 8 - line 24, column 44
    
        Cannot derive a type class instance for
                                       
          Data.Generic.Generic Hour
                                   
        since instances of this type class are not derivable.
    
    
      See https://github.com/purescript/documentation/blob/master/errors/CannotDerive.md for more information,
      or to contribute content related to this error.
    
    Error 3 of 3:
    
      at bower_components/purescript-datetime/src/Data/Time/Duration.purs line 12, column 8 - line 12, column 60
    
        Cannot derive a type class instance for
                                           
          Data.Generic.Generic Milliseconds
                                           
        since instances of this type class are not derivable.
    
    
      See https://github.com/purescript/documentation/blob/master/errors/CannotDerive.md for more information,
      or to contribute content related to this error.
    
    
    * ERROR: Subcommand terminated with exit code 1

Any ideas? Is the version Bower picks already "legacy"?

**Comment by paf31** [comment]
This is expected right now, since `Data.Generic` deriving was removed in preparation for 0.12, and the libraries have not been updated.

**Comment by paf31** [comment]
Sorry, just realized this is on `datetime`, not the compiler. Reopening.

**Comment by chexxor** [comment]
I can successfully build master branch of "purescript-datetime" using 0.11.6 and 0.11.7, I believe.
What's the work item here? To remove dependency on old generic and reimplement in new generic?

**Comment by hdgarrood** [comment]
That will need to happen at some point, yes. I'm actually not sure why this was reopened, since this seems to be the correct explanation to me:

> This is expected right now, since Data.Generic deriving was removed in preparation for 0.12, and the libraries have not been updated.

**Comment by garyb** [comment]
We might not even need to use any `Generic` now. For old-`Generic`, since it was required that all parts of a data structure were `Generic` to be able to use the `genericFoo` stuff, but that's no longer true with the new style.
