### ISSUE TITLE
proper Ord instances for Date / Time / DateTime

### ISSUE THREAD

**Issue by maackle** [purescript/purescript-datetime#70]
The `Ord` instance is derived for Time, Date, and DateTime, which doesn't represent their intuitive ordering. Is this just something that never got done, or is there a reason for this? It would be far more useful to have the ordering cascade from year -> month -> day -> hour -> minute -> second -> milliseconds.

I could write this if it's desirable. I'm going to have to write a true `lessThan` for my own purposes anyway.

**Comment by maackle** [comment]
Apologies, I didn't realize that the derived Ord works as expected because of the order of the values, and I had a bug in my code so I thought the derived Ord was to blame!

**Comment by garyb** [comment]
That's a relief, thanks for checking back in! I was pretty sure the `Ord` should have worked out with the field ordering in the constructors.
