### ISSUE TITLE
Why didn't expose ’Date’ constructor?

### ISSUE THREAD

**Issue by acple** [purescript/purescript-datetime#74]
`Time` constructor is already exposed but `Date` isn't.
I think it is very unreasonable.

```purescript
func (DateTime (Date y m d) (Time h mm s _)) = ?cannotdo
```

**Comment by garyb** [comment]
If `Date` is exported you can create gibberish dates (31st of November, for example), but that is not true of `Time`.

**Comment by acple** [comment]
Aoh I see, thats make sense...
I want it only for deconstruction but the constructor exposing is bad choice...
Or, sorry for other question here, are you planing to expose `DateRec` and `toRecord` later on? I can substitute for that.
