### ISSUE TITLE
Add a convenient way to get the `Millisecond`s between two `Instant`s

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript/purescript-datetime#98]
This is a use case I have often when timing things.
I would like to avoid running `unInstant` in application code. 

Maybe like this:

```purescript
-- | Get the amount of milliseconds between the first and second Instant
-- | for example:
-- | ```
-- | do
-- |   start <- Instant.now
-- |   aLongRunningEffect
-- |   end <- Instant.now
-- |   let duration = Instant.delta end start
-- |   log ("A long running effect took " <> show duration)
-- | ```
delta ∷ Instant → Instant → Milliseconds
delta i1 i2 = (unInstant i1) <> negateDuration (unInstant i2)
```

**Comment by hdgarrood** [comment]
This feels to me like it could be a nice use case for the Duration class?
```
delta :: forall a. Duration a => Instant -> Instant -> a
```

**Comment by i-am-the-slime** [comment]
Yes, but it risks to also be a bit annoying when trying to just log it with `show` for example, right?

**Comment by hdgarrood** [comment]
Yeah. Either way it's easy to get what you want. I guess the other `Instant` functions work in `Milliseconds` so maybe it'd make more sense to do the same here.
